language: node_js
node_js: '12'
env:
  global:
    - GIT_NAME="Domain Management"
    - GIT_EMAIL="domain.management@americastestkitchen.com"

install:
  - yarn

script:
  - yarn lint
  - yarn test
  - yarn build
  - yarn tsc

before_deploy:
  - if [ "$TRAVIS_BRANCH" == "main" ];then
    git checkout main;
    fi;

deploy:
  - provider: script
    script: if [ "$GH_TOKEN" != "false" ];then npx auto shipit; fi;
    skip-cleanup: true
    on:
      branch: main
